services:
  app:
    build: .
    restart: unless-stopped
    container_name: minurl_app
    ports:
      - "4000:4000"
    environment:
      - REDIS_ADDR=minurl_redis:6379
      - NATS_URL=nats://minurl_nats:4222
      - POSTGRES_DSN=postgres://postgres:pass123@minurl_db:5432/minurl?sslmode=disable
      - CLICKHOUSE_HOST=minurl_clickhouse
      - CLICKHOUSE_DB=minurl
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWD=
      - SNOWFLAKE_NODE_ID=1
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
      clickhouse_migrator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      nats:
        condition: service_started

  postgres:
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb
    container_name: minurl_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: minurl
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d minurl"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: minurl_migrator
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres:pass123@minurl_db:5432/minurl?sslmode=disable
      - GOOSE_DIR=/migrations
      - GOOSE_COMMAND=up
    volumes:
      - ./migrations/postgres:/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    container_name: minurl_clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - CLICKHOUSE_DB=minurl
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

  clickhouse_migrator:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: minurl_clickhouse_migrator
    environment:
      - GOOSE_DRIVER=clickhouse
      - GOOSE_DBSTRING=clickhouse://default:@minurl_clickhouse:9000/minurl
      - GOOSE_DIR=/migrations
      - GOOSE_COMMAND=up
    volumes:
      - ./migrations/clickhouse:/migrations:ro
    depends_on:
      clickhouse:
        condition: service_healthy

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    container_name: minurl_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # To give redis-stack time to fully boot up

  nats:
    image: nats:alpine
    restart: unless-stopped
    container_name: minurl_nats
    command: ["-js"] # Enable JetStream
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  db_data:
  clickhouse_data:
  clickhouse_logs:
  redis_data:
